# Generated by Django 3.0.7 on 2020-06-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20200609_0354'),
        ('suppliers', '0002_auto_20200608_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
