# Generated by Django 3.0.7 on 2020-06-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20200609_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
