# Generated by Django 3.0.7 on 2020-06-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20200611_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
