# Generated by Django 3.0.7 on 2020-06-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200609_1437'),
        ('suppliers', '0005_auto_20200611_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
