# Generated by Django 3.0.7 on 2020-06-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycomb_theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
