# Generated by Django 3.0.7 on 2020-06-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycomb_theme', '0001_initial'),
        ('inventory', '0002_auto_20200606_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easycomb_theme.Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easycomb_theme.City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
