# Generated by Django 3.0.7 on 2020-06-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easycomb_theme', '0001_initial'),
        ('inventory', '0003_auto_20200606_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easycomb_theme.Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easycomb_theme.City'),
        ),
    ]
