# Generated by Django 3.0.7 on 2020-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200606_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/default-product.jpg', upload_to='uploads/'),
        ),
    ]
