# Generated by Django 3.0.7 on 2020-06-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200606_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
