# Generated by Django 3.0.7 on 2020-06-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200609_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='product_list',
            field=models.ManyToManyField(through='inventory.ComboDetail', to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='combodetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.Product'),
        ),
    ]
