# Generated by Django 3.0.7 on 2020-06-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200609_1437'),
        ('orders', '0005_auto_20200609_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Combo'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_combos', to='orders.Order'),
        ),
    ]
