# Generated by Django 3.0.7 on 2020-06-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200609_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price_unit',
            field=models.FloatField(default=180),
            preserve_default=False,
        ),
    ]
