# Generated by Django 3.0.7 on 2020-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderdetail_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_combo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price_product',
            field=models.FloatField(default=0),
        ),
    ]
