# Generated by Django 3.0.7 on 2020-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Preparar'), ('R', 'Listo'), ('D', 'Entregado')], default='P', max_length=1),
        ),
    ]
