# Generated by Django 3.0.7 on 2020-06-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200609_1437'),
        ('orders', '0016_auto_20200620_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='combos',
            field=models.ManyToManyField(through='orders.OrderDetail', to='inventory.Combo'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_orders', to='inventory.Combo'),
        ),
    ]
